name: Earthquake Notification

on:
  schedule:
    - cron: "*/1 * * * *"   # 毎分実行
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run Earthquake Notification
        id: quake
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          LAST_EVENT_ID: ${{ secrets.LAST_EVENT_ID }}
        run: python telegrambot.py

      # Secrets 更新
      - name: Update LAST_EVENT_ID secret
        if: steps.quake.outputs.LAST_EVENT_ID_NEW != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const newEvent = process.env.LAST_EVENT_ID_NEW;
            await github.rest.actions.createOrUpdateRepoSecret({
              owner: context.repo.owner,
              repo: context.repo.repo,
              secret_name: "LAST_EVENT_ID",
              encrypted_value: newEvent
            });
